import { createI18n } from "vue-i18n";
import en from "element-plus/es/locale/lang/en";
import es from "element-plus/es/locale/lang/es";
import ja from "element-plus/es/locale/lang/ja";
import zhCn from "element-plus/es/locale/lang/zh-cn";

export type SupportedLocale = "en" | "zh-CN" | "ja" | "es";

export const localeOptions: Array<{ value: SupportedLocale; label: string; short: string }> = [
  { value: "en", label: "English", short: "EN" },
  { value: "zh-CN", label: "简体中文", short: "中文" },
  { value: "ja", label: "日本語", short: "日本語" },
  { value: "es", label: "Español", short: "ES" },
];

// Chinese is the product default because the primary audience is in China.
// The versioned key prevents an old English default from overriding this change.
const savedLocale = localStorage.getItem("ai-interviewer-locale-v2") as SupportedLocale | null;
const initialLocale: SupportedLocale = localeOptions.some((item) => item.value === savedLocale) ? savedLocale! : "zh-CN";

const messages = {
  en: {
    nav: { overview: "Overview", resume: "My Resume", jobs: "Jobs", practice: "Practice Room", settings: "Settings", workspace: "Workspace", support: "Support", coachOnline: "Interview coach online", ready: "Ready when you are", profile: "Profile", signOut: "Sign out", language: "Language", notifications: "Notifications", candidate: "Candidate" },
    common: { manage: "Manage", viewAll: "View all", begin: "Begin practice", back: "Back", export: "Export report", parsed: "Parsed", profileReady: "Profile ready", remove: "Remove" },
    login: { heroEyebrow: "YOUR NEXT ROLE STARTS HERE", heroTitle: "Turn preparation", heroAccent: "into confidence", heroDescription: "Practice with a focused AI interviewer, sharpen your story, and walk into every conversation prepared", quote: "The best interview prep feels like having a brilliant coach in your corner", quoteBy: "Interviewly method", eyebrow: "WELCOME BACK", title: "Ready to level up?", description: "Sign in to continue your interview journey.", account: "Account", accountPlaceholder: "Enter account", password: "Password", passwordPlaceholder: "Enter your password", remember: "Remember me", forgot: "Forgot password?", submit: "Sign in to workspace", demo: "Demo mode · Use your account and password to sign in", terms: "By continuing, you agree to our", termsLink: "Terms", privacy: "Privacy Policy", invalidAccount: "Please enter a valid account", requiredAccount: "Please enter your account", requiredPassword: "Please enter your password", passwordLength: "Password must be at least 8 characters", welcome: "Welcome back. Your workspace is ready." },
    dashboard: { date: "MONDAY, MARCH 23, 2026", greeting: "Good morning, {name}", subtitle: "Small, focused practice sessions create standout interviews.", start: "Start an interview", readiness: "Interview readiness", sessions: "Practice sessions", average: "Average score", fromLastWeek: "from last week", thisWeek: "this week", total: "total", topCandidates: "of candidates", foundation: "PROFILE FOUNDATION", resumeTitle: "Your resume", uploaded: "Uploaded Mar 20, 2026 · 2.4 MB", completeness: "Profile completeness", detected: "Detected strengths", recommended: "RECOMMENDED NEXT STEP", nextTitle: "System design", nextAccent: "pressure test", nextDescription: "Explore how you communicate trade-offs in a realistic architecture round.", progress: "YOUR PROGRESS", recent: "Recent interviews", interview1: "Senior Backend Engineer", interview2: "System Design Deep Dive", interview3: "Python & API Architecture", yesterday: "Yesterday, 4:30 PM", lastMonth: "Mar 18, 2026", earlier: "Mar 12, 2026" },
    resume: { eyebrow: "PROFILE FOUNDATION", title: "Make your resume work harder.", subtitle: "Your resume is the starting point for every personalized interview.", stepUpload: "STEP 01", uploadTitle: "Upload your resume", format: "PDF · Max 10 MB", drop: "Drop your resume here", browse: "browse files", fromComputer: "from your computer", onlyPdf: "Only PDF resumes are supported.", ready: "Ready to parse", parse: "Parse resume", reparse: "Re-parse resume", privacy: "Your resume is used only to personalize your practice sessions.", stepStatus: "STEP 02", statusTitle: "Parsing status", waiting: "Waiting for your resume", reading: "Reading your experience...", extracted: "Profile extracted", waitingDescription: "Upload a PDF to extract skills, projects, and experience.", extractedDescription: "Your experience has been organized into an interview-ready profile.", upload: "Upload", extract: "Extract", readyStep: "Ready", detected: "EXTRACTED PROFILE", strengths: "Detected strengths", skillsFound: "{count} skills found", addSkill: "+ Add skill", success: "Resume parsed successfully.", analyze: "AI analyze resume", reanalyze: "Re-analyze resume", analyzing: "Analyzing...", analysisSuccess: "Resume analysis completed.", aiAnalysis: "AI ANALYSIS", analysisTitle: "Capability profile", skills: "Skills", projects: "Projects", experience: "Experience", suggestions: "Suggestions", selectJob: "Select a job before generating questions.", selectJobPlaceholder: "Select a saved job", generateQuestions: "Generate interview questions", generatedQuestions: "GENERATED QUESTIONS", questionsTitle: "Personalized interview questions", questionGenerationSuccess: "Interview questions generated.", questionGenerationFailed: "Unable to generate interview questions.", jobsLoadFailed: "Unable to load saved jobs.", questionCategories: { technical: "Technical", project: "Project", behavioral: "Behavioral", system_design: "System design", role_fit: "Role fit" }, questionDifficulties: { easy: "Easy", medium: "Medium", hard: "Hard" } },
    job: { eyebrow: "TARGET ROLE", title: "Add a job description.", subtitle: "Save the roles you are preparing for and generate targeted interview questions.", newEyebrow: "NEW POSITION", formTitle: "Save a job", company: "Company", companyPlaceholder: "e.g. Acme Inc.", position: "Position", positionPlaceholder: "e.g. Senior Backend Engineer", description: "Job description", descriptionPlaceholder: "Paste the job description here...", save: "Save job", savedEyebrow: "SAVED POSITIONS", listTitle: "Your job descriptions", empty: "No saved jobs yet.", required: "Complete all job fields first.", success: "Job saved successfully.", saveFailed: "Unable to save job.", loadFailed: "Unable to load jobs." },
    interview: { live: "LIVE PRACTICE · SESSION #{id}", title: "Backend architecture deep dive", active: "Session active", coachNotes: "Coach notes", context: "INTERVIEW CONTEXT", role: "Senior Backend Engineer", question: "Question 2 of 8", questionProgress: "Question {current} of {total}", startTitle: "Start a live technical interview", startDescription: "Use your analyzed resume and a saved job description to begin a personalized interview.", noResume: "No resume found", selectJob: "Select a saved job", loadingHistory: "Loading interview history...", loadSetupFailed: "Unable to load interview setup", loadInterviewFailed: "Unable to load this interview", missingResources: "Upload and analyze a resume, then select a saved job first.", startFailed: "Unable to start interview", continueFailed: "Unable to continue the interview", ai: "Interviewly AI", you: "You", welcome: "Welcome to your practice room, Alex. I’ll be your interviewer today.", opening: "Let’s start with something familiar: walk me through a backend system you’re proud of building. What was the problem, and what decisions did you make?", answer: "I built an AI customer support system using FastAPI and RAG. The biggest challenge was keeping response latency predictable as our knowledge base grew.", followup: "That’s a strong starting point. How did you approach the latency challenge, and what trade-offs did you consider?", thinking: "Thinking...", prompts: "Try asking", prompt1: "Help me structure my answer", prompt2: "Give me a harder follow-up", prompt3: "What should I emphasize?", placeholder: "Type your answer...", hint: "Press Enter to send · Shift + Enter for a new line", reply: "Good direction. Keep the answer grounded in your role, the measurable outcome, and one decision you would make differently today." },
    report: { session: "SESSION REPORT · MARCH 21, 2026", title: "Senior Backend Engineer", subtitle: "A focused readout of your system design practice session.", overall: "OVERALL PERFORMANCE", headline: "Strong signal, keep sharpening.", description: "You communicated architecture clearly and showed good instincts around trade-offs. The next lift is making your impact more measurable.", benchmark: "Above role benchmark", versus: "+8 vs last session", confidence: "Confidence", depth: "Technical depth", strengthsEyebrow: "WHAT LANDED", strengths: "Your strengths", improveEyebrow: "NEXT LEVEL", improvements: "Areas to improve", strength1: "Clear system boundaries", strength2: "Strong API fundamentals", strength3: "Pragmatic trade-off thinking", improve1: "Quantify impact more often", improve2: "Explain failure modes earlier", improve3: "Close answers with a crisp summary", path: "YOUR LEARNING PATH", practice: "Recommended practice", viewPath: "View learning path", suggestion1: "Practice metrics storytelling", suggestion1Text: "Use latency, throughput, and adoption metrics to make your project impact memorable.", suggestion2: "Review distributed systems", suggestion2Text: "A focused review of queues and consistency will strengthen your architecture answers.", footer: "Keep practicing consistently. Your strongest answers are already close to exceptional." },
  },
  "zh-CN": {
    nav: { overview: "总览", resume: "我的简历", jobs: "岗位管理", practice: "模拟面试", settings: "设置", workspace: "工作区", support: "支持", coachOnline: "面试教练在线", ready: "随时准备开始", profile: "个人资料", signOut: "退出登录", language: "语言", notifications: "通知", candidate: "候选人" },
    common: { manage: "管理", viewAll: "查看全部", begin: "开始练习", back: "返回", export: "导出报告", parsed: "已解析", profileReady: "资料已就绪", remove: "移除" },
    login: { heroEyebrow: "你的下一份工作从这里开始", heroTitle: "让准备", heroAccent: "变成自信", heroDescription: "与专注的 AI 面试官练习，打磨你的表达，从容面对每一次面试", quote: "最好的面试准备，就像身边有一位出色的教练", quoteBy: "Interviewly 方法", eyebrow: "欢迎回来", title: "准备好提升了吗？", description: "登录后继续你的面试成长之旅。", account: "账号", accountPlaceholder: "输入账号", password: "密码", passwordPlaceholder: "输入密码", remember: "记住我", forgot: "忘记密码？", submit: "进入工作区", demo: "使用账号和密码登录", terms: "继续即表示你同意我们的", termsLink: "服务条款", privacy: "隐私政策", invalidAccount: "请输入有效账号", requiredAccount: "请输入账号", requiredPassword: "请输入密码", passwordLength: "密码至少需要 8 位", welcome: "欢迎回来，工作区已准备好。" },
    dashboard: { date: "2026 年 3 月 23 日 · 星期一", greeting: "你好，{name}", subtitle: "专注而持续的练习，能让你在面试中脱颖而出。", start: "开始面试", readiness: "面试准备度", sessions: "练习次数", average: "平均分", fromLastWeek: "较上周", thisWeek: "本周", total: "总计", topCandidates: "候选人排名", foundation: "个人资料基础", resumeTitle: "你的简历", uploaded: "上传于 2026 年 3 月 20 日 · 2.4 MB", completeness: "资料完整度", detected: "检测到的优势", recommended: "推荐下一步", nextTitle: "系统设计", nextAccent: "压力测试", nextDescription: "练习如何在真实架构题中表达权衡取舍。", progress: "你的进步", recent: "最近的面试", interview1: "高级后端工程师", interview2: "系统设计深入练习", interview3: "Python 与 API 架构", yesterday: "昨天 16:30", lastMonth: "2026 年 3 月 18 日", earlier: "2026 年 3 月 12 日" },
    resume: { eyebrow: "个人资料基础", title: "让你的简历发挥更大价值。", subtitle: "简历是每一次个性化面试的起点。", stepUpload: "步骤 01", uploadTitle: "上传你的简历", format: "PDF · 最大 10 MB", drop: "将简历拖放到这里", browse: "浏览文件", fromComputer: "从电脑中选择", onlyPdf: "只支持 PDF 简历。", ready: "准备解析", parse: "解析简历", reparse: "重新解析简历", privacy: "简历仅用于生成个性化练习内容。", stepStatus: "步骤 02", statusTitle: "解析状态", waiting: "等待上传简历", reading: "正在读取你的经历……", extracted: "资料已提取", waitingDescription: "上传 PDF 以提取技能、项目和工作经历。", extractedDescription: "你的经历已整理为面试资料。", upload: "上传", extract: "提取", readyStep: "就绪", detected: "提取的资料", strengths: "检测到的优势", skillsFound: "发现 {count} 项技能", addSkill: "+ 添加技能", success: "简历解析成功。", analyze: "AI分析简历", reanalyze: "重新分析简历", analyzing: "正在分析……", analysisSuccess: "简历分析完成。", aiAnalysis: "AI分析", analysisTitle: "能力画像", skills: "技能", projects: "项目经验", experience: "工作经历", suggestions: "改进建议", selectJob: "请先选择岗位再生成面试题。", selectJobPlaceholder: "选择已保存的岗位", generateQuestions: "生成面试题", generatedQuestions: "生成的面试题", questionsTitle: "个性化面试题", questionGenerationSuccess: "面试题生成成功。", questionGenerationFailed: "面试题生成失败。", jobsLoadFailed: "岗位加载失败。", questionCategories: { technical: "技术", project: "项目经验", behavioral: "行为面", system_design: "系统设计", role_fit: "岗位匹配" }, questionDifficulties: { easy: "简单", medium: "中等", hard: "困难" } },
    job: { eyebrow: "目标岗位", title: "添加岗位描述。", subtitle: "保存你正在准备的岗位，并生成针对性的面试题。", newEyebrow: "新增岗位", formTitle: "保存岗位", company: "公司", companyPlaceholder: "例如：某某科技", position: "职位", positionPlaceholder: "例如：高级后端工程师", description: "岗位JD", descriptionPlaceholder: "请粘贴岗位描述……", save: "保存岗位", savedEyebrow: "已保存岗位", listTitle: "你的岗位描述", empty: "暂未保存岗位。", required: "请先填写完整的岗位信息。", success: "岗位保存成功。", saveFailed: "岗位保存失败。", loadFailed: "岗位加载失败。" },
    interview: { live: "实时练习 · 第 {id} 场", title: "后端架构深入练习", active: "面试进行中", coachNotes: "教练笔记", context: "面试背景", role: "高级后端工程师", question: "第 2 个问题，共 8 个问题", questionProgress: "第 {current} 个问题，共 {total} 个问题", startTitle: "开始技术面试", startDescription: "使用已经分析的简历和已保存的岗位描述，开始个性化面试。", noResume: "暂未找到简历", selectJob: "选择已保存的岗位", loadingHistory: "正在加载面试记录……", loadSetupFailed: "无法加载面试准备信息", loadInterviewFailed: "无法加载本场面试", missingResources: "请先上传并分析简历，再选择一个已保存的岗位。", startFailed: "无法开始面试", continueFailed: "无法继续面试", ai: "Interviewly AI", you: "你", welcome: "欢迎来到练习室，Alex。今天由我担任你的面试官。", opening: "先从熟悉的话题开始：请介绍一个你引以为傲的后端系统。它解决了什么问题？你做了哪些关键决策？", answer: "我使用 FastAPI 和 RAG 构建了一个 AI 客服系统。最大的挑战是在知识库不断增长时保持响应延迟稳定。", followup: "这是一个很好的开始。你如何解决延迟问题？当时考虑了哪些权衡？", thinking: "思考中……", prompts: "你可以这样问", prompt1: "帮我组织答案", prompt2: "给我一个更难的追问", prompt3: "我应该强调什么？", placeholder: "输入你的回答……", hint: "按 Enter 发送 · Shift + Enter 换行", reply: "方向很好。让回答落到你的具体职责、可衡量结果，以及一个今天会做出不同选择的决策。" },
    report: { session: "面试报告 · 2026 年 3 月 21 日", title: "高级后端工程师", subtitle: "这是本次系统设计练习的重点反馈。", overall: "综合表现", headline: "表现很强，继续打磨。", description: "你清晰地表达了架构，也展现了良好的权衡意识。下一步可以让成果更加量化。", benchmark: "高于岗位基准", versus: "较上次提升 8 分", confidence: "表达自信度", depth: "技术深度", strengthsEyebrow: "表现亮点", strengths: "你的优势", improveEyebrow: "继续提升", improvements: "待提升方向", strength1: "系统边界清晰", strength2: "API 基础扎实", strength3: "能够做出务实的权衡", improve1: "更多量化业务影响", improve2: "更早解释故障模式", improve3: "用简洁总结收尾", path: "你的学习路径", practice: "推荐练习", viewPath: "查看学习路径", suggestion1: "练习用数据讲故事", suggestion1Text: "使用延迟、吞吐量和用户增长等指标，让项目影响更有说服力。", suggestion2: "复习分布式系统", suggestion2Text: "重点复习队列和一致性，将进一步提升你的架构回答。", footer: "保持稳定练习，你最强的回答已经接近优秀。" },
  },
  ja: {
    nav: { overview: "概要", resume: "履歴書", jobs: "求人", practice: "練習ルーム", settings: "設定", workspace: "ワークスペース", support: "サポート", coachOnline: "面接コーチがオンライン", ready: "いつでも始められます", profile: "プロフィール", signOut: "ログアウト", language: "言語", notifications: "通知", candidate: "候補者" },
    common: { manage: "管理", viewAll: "すべて見る", begin: "練習を始める", back: "戻る", export: "レポートを出力", parsed: "解析済み", profileReady: "準備完了", remove: "削除" },
    login: { heroEyebrow: "次のキャリアはここから", heroTitle: "準備を", heroAccent: "自信に変える", heroDescription: "AI 面接官と練習し、あなたのストーリーを磨き、面接に自信を持って臨みましょう", quote: "最高の面接準備は、優秀なコーチがそばにいるようなものです", quoteBy: "Interviewly メソッド", eyebrow: "おかえりなさい", title: "レベルアップの準備はできましたか？", description: "サインインして面接の旅を続けましょう。", account: "アカウント", accountPlaceholder: "アカウントを入力", password: "パスワード", passwordPlaceholder: "パスワードを入力", remember: "ログイン状態を保存", forgot: "パスワードを忘れた？", submit: "ワークスペースへ", demo: "アカウントとパスワードでログインできます", terms: "続行すると、次に同意したことになります：", termsLink: "利用規約", privacy: "プライバシーポリシー", invalidAccount: "有効なアカウントを入力してください", requiredAccount: "アカウントを入力してください", requiredPassword: "パスワードを入力してください", passwordLength: "パスワードは 8 文字以上です", welcome: "おかえりなさい。ワークスペースの準備ができました。" },
    dashboard: { date: "2026年3月23日 · 月曜日", greeting: "おはようございます、{name}さん", subtitle: "小さく集中した練習が、面接での自信につながります。", start: "面接を始める", readiness: "面接準備度", sessions: "練習セッション", average: "平均スコア", fromLastWeek: "先週から", thisWeek: "今週", total: "合計", topCandidates: "候補者中", foundation: "プロフィール", resumeTitle: "あなたの履歴書", uploaded: "2026年3月20日アップロード · 2.4 MB", completeness: "プロフィール完成度", detected: "検出された強み", recommended: "おすすめの次のステップ", nextTitle: "システム設計", nextAccent: "実践テスト", nextDescription: "現実的なアーキテクチャ面接でトレードオフの伝え方を練習します。", progress: "あなたの進捗", recent: "最近の面接", interview1: "シニアバックエンドエンジニア", interview2: "システム設計ディープダイブ", interview3: "Python と API アーキテクチャ", yesterday: "昨日 16:30", lastMonth: "2026年3月18日", earlier: "2026年3月12日" },
    resume: { eyebrow: "プロフィール", title: "履歴書をもっと活かしましょう。", subtitle: "履歴書はパーソナライズされた面接の出発点です。", stepUpload: "STEP 01", uploadTitle: "履歴書をアップロード", format: "PDF · 最大 10 MB", drop: "履歴書をここにドロップ", browse: "ファイルを参照", fromComputer: "コンピューターから", onlyPdf: "PDF の履歴書のみ対応しています。", ready: "解析の準備完了", parse: "履歴書を解析", reparse: "再解析", privacy: "履歴書は練習内容のパーソナライズにのみ使用されます。", stepStatus: "STEP 02", statusTitle: "解析ステータス", waiting: "履歴書を待っています", reading: "経験を読み込んでいます…", extracted: "プロフィールを抽出しました", waitingDescription: "PDF をアップロードしてスキルや経験を抽出します。", extractedDescription: "経験が面接用プロフィールに整理されました。", upload: "アップロード", extract: "抽出", readyStep: "準備完了", detected: "抽出されたプロフィール", strengths: "検出された強み", skillsFound: "{count} 個のスキル", addSkill: "+ スキルを追加", success: "履歴書の解析に成功しました。", analyze: "AI分析", reanalyze: "再分析", analyzing: "分析中…", analysisSuccess: "履歴書の分析が完了しました。", aiAnalysis: "AI分析", analysisTitle: "能力プロフィール", skills: "スキル", projects: "プロジェクト", experience: "経験", suggestions: "提案", selectJob: "質問を生成する前に求人を選択してください。", selectJobPlaceholder: "保存済みの求人を選択", generateQuestions: "面接質問を生成", generatedQuestions: "生成された質問", questionsTitle: "パーソナライズされた面接質問", questionGenerationSuccess: "面接質問を生成しました。", questionGenerationFailed: "面接質問の生成に失敗しました。", jobsLoadFailed: "求人の読み込みに失敗しました。", questionCategories: { technical: "技術", project: "プロジェクト", behavioral: "行動", system_design: "システム設計", role_fit: "職種適合" }, questionDifficulties: { easy: "易しい", medium: "中級", hard: "難しい" } },
    job: { eyebrow: "対象ポジション", title: "求人情報を追加", subtitle: "準備中のポジションを保存し、対象に合わせた面接質問を生成します。", newEyebrow: "新しいポジション", formTitle: "求人を保存", company: "会社", companyPlaceholder: "例：Acme Inc.", position: "ポジション", positionPlaceholder: "例：シニアバックエンドエンジニア", description: "求人情報", descriptionPlaceholder: "求人情報を貼り付けてください…", save: "求人を保存", savedEyebrow: "保存済みポジション", listTitle: "あなたの求人情報", empty: "保存された求人はありません。", required: "すべての項目を入力してください。", success: "求人を保存しました。", saveFailed: "求人の保存に失敗しました。", loadFailed: "求人の読み込みに失敗しました。" },
    interview: { live: "LIVE 練習 · セッション #{id}", title: "バックエンドアーキテクチャ深掘り", active: "セッション中", coachNotes: "コーチノート", context: "面接コンテキスト", role: "シニアバックエンドエンジニア", question: "8問中 2問目", ai: "Interviewly AI", you: "あなた", welcome: "練習ルームへようこそ、Alexさん。今日は私が面接官を務めます。", opening: "まずは身近な話題から。あなたが誇りに思うバックエンドシステムを教えてください。どんな課題を解決し、どんな決断をしましたか？", answer: "FastAPI と RAG を使って AI カスタマーサポートシステムを構築しました。知識ベースが大きくなる中で応答遅延を予測可能に保つことが最大の課題でした。", followup: "良いスタートです。遅延の課題にどう取り組み、どんなトレードオフを考えましたか？", thinking: "考え中…", prompts: "質問してみる", prompt1: "回答を整理して", prompt2: "難しい追質問をして", prompt3: "何を強調すべき？", placeholder: "回答を入力…", hint: "Enter で送信 · Shift + Enter で改行", reply: "良い方向です。役割、測定可能な成果、そして今なら違う選択をする決断に結びつけて答えましょう。" },
    report: { session: "面接レポート · 2026年3月21日", title: "シニアバックエンドエンジニア", subtitle: "今回のシステム設計練習のフィードバックです。", overall: "総合パフォーマンス", headline: "強い印象です。さらに磨きましょう。", description: "アーキテクチャを明確に伝え、トレードオフにも良い判断を示しました。次は成果をより数値化しましょう。", benchmark: "役割の基準以上", versus: "前回より +8", confidence: "自信度", depth: "技術的な深さ", strengthsEyebrow: "良かった点", strengths: "あなたの強み", improveEyebrow: "次のレベル", improvements: "改善ポイント", strength1: "システム境界が明確", strength2: "API の基礎が強い", strength3: "現実的なトレードオフ判断", improve1: "影響をより数値化する", improve2: "障害モードを早めに説明する", improve3: "明確な要約で締める", path: "学習パス", practice: "おすすめの練習", viewPath: "学習パスを見る", suggestion1: "数字でストーリーを語る", suggestion1Text: "遅延、スループット、利用率などを使ってプロジェクトの成果を伝えましょう。", suggestion2: "分散システムを復習", suggestion2Text: "キューと一貫性を復習すると、アーキテクチャの回答が強くなります。", footer: "継続して練習しましょう。あなたの強みは素晴らしい回答に近づいています。" },
  },
  es: {
    nav: { overview: "Resumen", resume: "Mi currículum", jobs: "Puestos", practice: "Sala de práctica", settings: "Configuración", workspace: "Espacio de trabajo", support: "Soporte", coachOnline: "Coach de entrevistas online", ready: "Listo cuando tú quieras", profile: "Perfil", signOut: "Cerrar sesión", language: "Idioma", notifications: "Notificaciones", candidate: "Candidato" },
    common: { manage: "Gestionar", viewAll: "Ver todo", begin: "Comenzar práctica", back: "Volver", export: "Exportar informe", parsed: "Analizado", profileReady: "Perfil listo", remove: "Eliminar" },
    login: { heroEyebrow: "TU PRÓXIMO PUESTO EMPIEZA AQUÍ", heroTitle: "Convierte la preparación", heroAccent: "en confianza", heroDescription: "Practica con un entrevistador de IA, mejora tu historia y llega preparado a cada conversación", quote: "La mejor preparación se siente como tener un gran coach a tu lado", quoteBy: "Método Interviewly", eyebrow: "BIENVENIDO DE NUEVO", title: "¿Listo para mejorar?", description: "Inicia sesión para continuar tu camino.", account: "Cuenta", accountPlaceholder: "Introduce tu cuenta", password: "Contraseña", passwordPlaceholder: "Introduce tu contraseña", remember: "Recordarme", forgot: "¿Olvidaste tu contraseña?", submit: "Entrar al espacio", demo: "Inicia sesión con tu cuenta y contraseña", terms: "Al continuar aceptas nuestros", termsLink: "Términos", privacy: "Política de privacidad", invalidAccount: "Introduce una cuenta válida", requiredAccount: "Introduce tu cuenta", requiredPassword: "Introduce tu contraseña", passwordLength: "La contraseña debe tener al menos 8 caracteres", welcome: "Bienvenido de nuevo. Tu espacio está listo." },
    dashboard: { date: "LUNES, 23 DE MARZO DE 2026", greeting: "Buenos días, {name}", subtitle: "Las sesiones breves y constantes crean entrevistas memorables.", start: "Comenzar entrevista", readiness: "Preparación para entrevistas", sessions: "Sesiones de práctica", average: "Puntuación media", fromLastWeek: "desde la semana pasada", thisWeek: "esta semana", total: "en total", topCandidates: "de candidatos", foundation: "BASE DEL PERFIL", resumeTitle: "Tu currículum", uploaded: "Subido el 20 de marzo de 2026 · 2.4 MB", completeness: "Completitud del perfil", detected: "Fortalezas detectadas", recommended: "SIGUIENTE PASO RECOMENDADO", nextTitle: "Diseño de sistemas", nextAccent: "prueba de presión", nextDescription: "Explora cómo comunicas decisiones y trade-offs en una ronda realista.", progress: "TU PROGRESO", recent: "Entrevistas recientes", interview1: "Ingeniero Backend Senior", interview2: "Profundización en diseño de sistemas", interview3: "Arquitectura de Python y APIs", yesterday: "Ayer, 16:30", lastMonth: "18 de marzo de 2026", earlier: "12 de marzo de 2026" },
    resume: { eyebrow: "BASE DEL PERFIL", title: "Haz que tu currículum trabaje más.", subtitle: "Tu currículum es el punto de partida de cada entrevista personalizada.", stepUpload: "PASO 01", uploadTitle: "Sube tu currículum", format: "PDF · Máx. 10 MB", drop: "Suelta tu currículum aquí", browse: "explora archivos", fromComputer: "desde tu ordenador", onlyPdf: "Solo se admiten currículums PDF.", ready: "Listo para analizar", parse: "Analizar currículum", reparse: "Analizar de nuevo", privacy: "Tu currículum solo se usa para personalizar tus prácticas.", stepStatus: "PASO 02", statusTitle: "Estado del análisis", waiting: "Esperando tu currículum", reading: "Leyendo tu experiencia…", extracted: "Perfil extraído", waitingDescription: "Sube un PDF para extraer habilidades, proyectos y experiencia.", extractedDescription: "Tu experiencia se ha organizado en un perfil listo para entrevistas.", upload: "Subir", extract: "Extraer", readyStep: "Listo", detected: "PERFIL EXTRAÍDO", strengths: "Fortalezas detectadas", skillsFound: "{count} habilidades encontradas", addSkill: "+ Añadir habilidad", success: "Currículum analizado correctamente.", analyze: "Analizar con IA", reanalyze: "Analizar de nuevo", analyzing: "Analizando…", analysisSuccess: "Análisis del currículum completado.", aiAnalysis: "ANÁLISIS DE IA", analysisTitle: "Perfil de capacidades", skills: "Habilidades", projects: "Proyectos", experience: "Experiencia", suggestions: "Sugerencias", selectJob: "Selecciona un puesto antes de generar preguntas.", selectJobPlaceholder: "Selecciona un puesto guardado", generateQuestions: "Generar preguntas", generatedQuestions: "PREGUNTAS GENERADAS", questionsTitle: "Preguntas de entrevista personalizadas", questionGenerationSuccess: "Preguntas generadas correctamente.", questionGenerationFailed: "No se pudieron generar las preguntas.", jobsLoadFailed: "No se pudieron cargar los puestos.", questionCategories: { technical: "Técnica", project: "Proyecto", behavioral: "Conductual", system_design: "Diseño de sistemas", role_fit: "Encaje con el puesto" }, questionDifficulties: { easy: "Fácil", medium: "Media", hard: "Difícil" } },
    job: { eyebrow: "PUESTO OBJETIVO", title: "Añade una descripción de puesto.", subtitle: "Guarda los puestos que estás preparando y genera preguntas específicas.", newEyebrow: "NUEVO PUESTO", formTitle: "Guardar puesto", company: "Empresa", companyPlaceholder: "p. ej. Acme Inc.", position: "Puesto", positionPlaceholder: "p. ej. Ingeniero Backend Senior", description: "Descripción del puesto", descriptionPlaceholder: "Pega aquí la descripción del puesto…", save: "Guardar puesto", savedEyebrow: "PUESTOS GUARDADOS", listTitle: "Tus descripciones", empty: "Aún no hay puestos guardados.", required: "Completa primero todos los campos.", success: "Puesto guardado correctamente.", saveFailed: "No se pudo guardar el puesto.", loadFailed: "No se pudieron cargar los puestos." },
    interview: { live: "PRÁCTICA EN VIVO · SESIÓN #{id}", title: "Profundización en arquitectura backend", active: "Sesión activa", coachNotes: "Notas del coach", context: "CONTEXTO DE ENTREVISTA", role: "Ingeniero Backend Senior", question: "Pregunta 2 de 8", ai: "Interviewly AI", you: "Tú", welcome: "Bienvenido a tu sala de práctica, Alex. Hoy seré tu entrevistador.", opening: "Empecemos con algo familiar: cuéntame sobre un sistema backend que te enorgullezca. ¿Qué problema resolvía y qué decisiones tomaste?", answer: "Construí un sistema de soporte al cliente con FastAPI y RAG. El mayor reto fue mantener predecible la latencia mientras crecía nuestra base de conocimiento.", followup: "Buen comienzo. ¿Cómo abordaste la latencia y qué trade-offs consideraste?", thinking: "Pensando…", prompts: "Prueba a preguntar", prompt1: "Ayúdame a estructurar la respuesta", prompt2: "Hazme una pregunta más difícil", prompt3: "¿Qué debería enfatizar?", placeholder: "Escribe tu respuesta…", hint: "Pulsa Enter para enviar · Shift + Enter para una nueva línea", reply: "Buen enfoque. Apóyate en tu rol, el resultado medible y una decisión que hoy tomarías de otra manera." },
    report: { session: "INFORME DE SESIÓN · 21 DE MARZO DE 2026", title: "Ingeniero Backend Senior", subtitle: "Un resumen de tu sesión de práctica de diseño de sistemas.", overall: "RENDIMIENTO GENERAL", headline: "Una señal fuerte, sigue puliendo.", description: "Comunicaste la arquitectura con claridad y mostraste buen criterio sobre los trade-offs. El siguiente paso es hacer más medible tu impacto.", benchmark: "Por encima del estándar", versus: "+8 frente a la sesión anterior", confidence: "Confianza", depth: "Profundidad técnica", strengthsEyebrow: "LO QUE FUNCIONÓ", strengths: "Tus fortalezas", improveEyebrow: "SIGUIENTE NIVEL", improvements: "Áreas de mejora", strength1: "Límites del sistema claros", strength2: "Fundamentos de API sólidos", strength3: "Pensamiento pragmático sobre trade-offs", improve1: "Cuantifica más el impacto", improve2: "Explica antes los fallos posibles", improve3: "Cierra con un resumen claro", path: "TU RUTA DE APRENDIZAJE", practice: "Práctica recomendada", viewPath: "Ver ruta de aprendizaje", suggestion1: "Practica contar historias con métricas", suggestion1Text: "Usa latencia, rendimiento y adopción para hacer memorable el impacto de tu proyecto.", suggestion2: "Repasa sistemas distribuidos", suggestion2Text: "Un repaso de colas y consistencia reforzará tus respuestas de arquitectura.", footer: "Sigue practicando. Tus mejores respuestas ya están cerca de ser excepcionales." },
  },
};

export const i18n = createI18n({
  legacy: false,
  locale: initialLocale,
  fallbackLocale: "en",
  globalInjection: true,
  messages,
});

export const elementLocales = { en, "zh-CN": zhCn, ja, es };

export function setLocale(locale: SupportedLocale) {
  i18n.global.locale.value = locale;
  localStorage.setItem("ai-interviewer-locale-v2", locale);
}
